#### scrape toucanet rating at a particular point in time

library(rvest)
library(lubridate)
library(ggplot2)
library(plotly)

url.stem <- "http://www.toucanet.com/archives/"
name.map.file <- "Scrabble_player_alias - Sheet1.csv"

path.common.data <- "C:/Users/Ricky/Documents/GitHub/Scrabble/common_data"

datepage <- "19 Sep 2015"
dp <- dmy(datepage)

target.url <-
  paste0(url.stem, year(dp), "/",
         formatC(month(dp), width=2, flag="0"), 
         day(dp),"/ratings.html")

raw.page <- read_html(target.url)

tb <- html_table(raw.page)[[1]]
# change encoding
tb <- as.data.frame(sapply(tb, iconv, "UTF-8", "ASCII"))

#clean up spaces
tb <- tb[!is.na(tb$Games),]    # only care about members who have played

# clean up the column names
tb <- tb[, -2]   # empty column removed
tb <- tb[, !(names(tb) %in% c("Member until"))]
names(tb)[2:3] <- c("Title", "Name")


# read mapping
alias.map <- read.csv(file.path(path.common.data, name.map.file), row.names = NULL)
names(alias.map) <- c("Name", "Standard.Name")

# get correct names for rating
fs <- merge(tb, alias.map)
fs <- fs[, !(names(fs) == "Name")]
names(fs)[names(fs)=="Standard.Name"] <- "name"   # rename for next join

# join with sum.stats generated by csv_to_tou.R
tou.name <- "Ro16.TOU"
sum.stats <- read.csv(paste0(tou.name, ".stat.csv"), row.names=NULL)
ss <- merge(sum.stats, fs)
bingos <- read.csv(paste0(tou.name, ".bingos.csv"), row.names=NULL)


bingsources <- 7:9   # list of bingo length to read in

full.bingo <- do.call(rbind,
  lapply(bingsources, function(x)
    read.table(file.path(path.common.data, paste0(x, "letter_prob.txt")))
    ))

names(full.bingo) <- c("word", "prob")
full.bingo$CSW15 <- grepl("[+]", full.bingo$word)   # identify CSW15
full.bingo$word <- gsub("[+]", "", full.bingo$word)

#### enrich played bingos
# phoney
bingos$phoney <- grepl("[*]", bingos$bingo)    # this assumes phoney declared
# play through string
playthrough <- gregexpr("\\(.+\\)", bingos$bingo)  # get the locations
bingos$playthrough.loc <- sapply(playthrough, paste, collapse=";")
bingos$playthrough.loc[bingos$playthrough.loc=="-1"] <- ""
bingos$playthrough.str <-   # if separate strings, split by ;
  sapply(regmatches(bingos$bingo, playthrough), paste, collapse=";")

# cleanup
bingos$playthrough.str <- gsub("[()]", "", bingos$playthrough.str)
bingos$bingo <- gsub("[()*]", "", bingos$bingo)
bingos$no <- as.integer(gsub("[[:alpha:]]", "", bingos$no))

# playthrough not applicable for 7 letter
# not applicable marked as blank. applicable but not available marked as NA
idx7let <- nchar(bingos$bingo)==7
bingos[!idx7let & nchar(bingos$playthrough.str)==0,
       names(bingos) %in% c("playthrough.loc", "playthrough.str")] <- NA

# blank declared?
blanks <- do.call(rbind,   # do call to force into two columns
                  gregexpr("[[:lower:]]+", bingos$bingo))
# cleanup
blanks[blanks == -1] <- NA   # no blanks, NA
blanks[blanks[, 1] == blanks[, 2], 2] <- 0   # if only one blank, empty
colnames(blanks) <- c("blank1", "blank2")
bingos <- cbind(bingos, blanks)
bingos$bingo <- toupper(bingos$bingo)

# get probabilities
bingos <- merge(bingos, full.bingo, by.x="bingo", by.y="word",
                all.x=T)


#plot
p <- ggplot(bingos, aes(x=name)) +
  geom_point(aes(y=prob)) +
  coord_polar()

pl <- ggplotly(p)

psc <- plot_ly(bingos, type="scatter",x=prob, y=name, mode="markers", hoverinfo="bingo+score")
