#########################################
##### read output from GoogleTrends generated by browser_gtrend
#########################################

read.trendfile <- function(fn) {
  cat(fn)
  
  #initialise
  freq <- reg <- sch <- numeric(0)
  
  f.con <- readLines(fn)
  # remove empty lines
  f.con <- f.con[f.con!=""]
  
  #extract the word searched
  word <- toupper(gsub("Web Search interest: ", "", f.con[1]))

  #skip if file two lines only, i.e. no data
  if (length(f.con) > 2) {
    #get positions of sections, based on headers
    freq.h <- c("StartDate", "RelFreq")
    freq.st <- grep("Interest over time", f.con) + 2
    reg.loc <- grep("Region", f.con)
    city.loc <- grep("Top cities", f.con)
    topsch.loc <- grep("Top searches", f.con)
    rising.loc <- grep("Rising searches", f.con)
    freq.end <- if(length(reg.loc)>0) reg.loc - 2 else
      if(length(topsch.loc)>0) topsch.loc - 1 else
        length(f.con)
    # freq.end <- grep("Region", f.con) - 2
    reg.h <- c("Region", "RelFreq")
    reg.st <- reg.loc + 1
    reg.end <- if(length(city.loc)>0) city.loc - 1 else
      if(length(topsch.loc)>0) topsch.loc - 1 else
        length(f.con)
    #reg.st <- freq.end + 3
    #reg.end <- grep("Top cities", f.con) - 1
    sch.h <- c("SearchTerm", "RelFreq")
    sch.st <- topsch.loc + 1
    sch.end <- if(length(rising.loc)>0) rising.loc - 1 else
      length(f.con)
    #sch.st <- grep("Top searches", f.con) + 1
    #sch.end <- grep("Rising searches", f.con) - 1

    if (length(freq.st)!=0) {
      freq <- read.csv(text=f.con[freq.st:freq.end], header=FALSE)
      names(freq) <- freq.h
    }
    
    if (length(reg.st)!=0) {
      reg <- read.csv(text=f.con[reg.st:reg.end], header=FALSE)
      names(reg) <- reg.h
    }
    
    if (length(sch.st)!=0) {
      sch <- read.csv(text=f.con[sch.st:sch.end], header=FALSE)
      names(sch) <- sch.h  
    }
  }
  
  trends <- list(word=word, freq=freq, region=reg, search=sch)
  return(assign(word, trends))  # change list name to be the word in variable word
}

last.batch <- 9
fnames <- character(0)
for (batch in 1:last.batch) {
  folder <- file.path("data", paste("batch", batch))
  fnames <- c(fnames, file.path(folder, list.files(folder)))
}

trends <- sapply(fnames, read.trendfile, simplify=FALSE) # using sapply to assign name to list (filename)
names(trends) <- sapply(trends, function(x) x$word)

save(trends, file="List_word_trends.RData")
